// Flat config for the Expo companion.
//
// It exists because the root config's ignore list said `'mobile/**' —
// separate package, own deps and own lint script`, describing a setup
// that was not there. mobile/ had a lint SCRIPT and no config and no
// eslint dependency, so `npm run lint` resolved eslint from the root
// node_modules, ESLint 9 walked up to the root config, found mobile/
// ignored there, and exited 1 with "all of the files matching the glob
// pattern '.' are ignored". Zero files linted, non-zero exit, and the
// two new screens in this branch were checked by nothing.
//
// Plugins are imported here and resolve up to the ROOT node_modules —
// there is deliberately no second eslint install in this package. A flat
// config imports its own plugins, so Node resolution does the work and
// mobile/ stays free of a duplicate toolchain.
//
// Severity policy matches the root's, for the same reasons: error for
// near-certain defects, warn where the honest fix is case-by-case.
import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import reactHooks from 'eslint-plugin-react-hooks';
import globals from 'globals';

export default tseslint.config(
  {
    ignores: [
      'node_modules/**',
      // Regenerated by `expo prebuild` — this is a CNG project, so
      // nothing here is hand-written or worth linting.
      'ios/**',
      'android/**',
      '.expo/**',
      'expo-env.d.ts',
      '**/*.ipa',
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  {
    files: ['**/*.{ts,tsx}'],
    plugins: { 'react-hooks': reactHooks },
    languageOptions: {
      // React Native's runtime is neither browser nor node: `fetch`,
      // `console` and the timer functions are there, `window` and `fs`
      // are not. `globals.browser` is the closest honest approximation
      // and is what Expo's own config uses.
      globals: { ...globals.browser, ...globals.es2021, __DEV__: 'readonly' },
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      'react-hooks/exhaustive-deps': 'warn',
      '@typescript-eslint/no-unused-vars': ['error', {
        argsIgnorePattern: '^_',
        varsIgnorePattern: '^_',
        caughtErrorsIgnorePattern: '^_',
        destructuredArrayIgnorePattern: '^_',
      }],
      '@typescript-eslint/no-explicit-any': 'warn',
      // React Native uses `require()` as a language feature, not as a
      // module-system fallback: Metro resolves `require('../assets/x.png')`
      // into an asset reference at bundle time, and a lazy `require` of a
      // native module is how a screen degrades when that module is not in
      // the dev client yet. Neither has an import form.
      '@typescript-eslint/no-require-imports': 'off',
    },
  },

  {
    // Terminal output is ANSI, and stripping it means matching the escape
    // characters. A control character in THIS regex is the subject matter.
    files: ['app/terminal-detail.tsx', 'lib/terminal*.ts'],
    rules: { 'no-control-regex': 'off' },
  },

  {
    // Build scripts run under Node, not the RN runtime.
    files: ['scripts/**/*.{js,mjs,cjs}'],
    languageOptions: { globals: globals.node, sourceType: 'commonjs' },
    rules: { '@typescript-eslint/no-require-imports': 'off' },
  },
);
