/**
 * Phase 32 status as data (the owner's ask, 2026-09-30).
 *
 * The Now block and the checklist were hand-kept Markdown in
 * `docs/PHASE-32-LOG.md`, with the same facts again on the status page, and
 * they drifted (a Now block still describing the step before). They live in
 * `docs/PHASE-32-STATUS.yaml` now: hand-edited, one entry per step, with its
 * id, status and PRs, so a program can read what is merged and what is next.
 * `npm run status` writes the LOG's Now and Checklist sections from it, and
 * a unit test fails when the LOG disagrees, as the inventory does for
 * `PHASE-32-VERIFICATION.md`. The dated entries stay prose in the LOG.
 */

import { parse } from 'yaml';

export const ITEM_STATUSES = ['todo', 'building', 'in_review', 'done'] as const;
export type ItemStatus = typeof ITEM_STATUSES[number];

export interface Item {
  /** The step's id when it has one: `B7.4`, `0.4c-1`, `HD1`. */
  id?: string;
  title: string;
  status: ItemStatus;
  /** The pull requests that carried it, in order. */
  prs?: number[];
  /** A follow-up: something found on the way, not a planned step. */
  followUp?: boolean;
  items?: Item[];
}

export interface Section { title: string; items: Item[] }

export interface Now {
  step: string;
  status: string;
  next: string;
  blockers: string;
  branch: string;
  updated: string;
}

export interface Status { now: Now; sections: Section[] }

export const START = '<!-- status:start — generated by `npm run status` from docs/PHASE-32-STATUS.yaml; edit that file, not this block -->';
export const END = '<!-- status:end -->';

/** Why the status cannot be used, one sentence per problem; empty when it can. */
export function problems(s: Status): string[] {
  const out: string[] = [];
  const nowKeys: Array<keyof Now> = ['step', 'status', 'next', 'blockers', 'branch', 'updated'];
  for (const k of nowKeys) if (typeof s.now?.[k] !== 'string' || !s.now[k].trim()) out.push(`now.${k} is missing.`);
  const seen = new Set<string>();
  const walk = (items: Item[], where: string) => {
    for (const it of items ?? []) {
      const name = it.id ?? it.title?.slice(0, 40);
      if (!it.title?.trim()) out.push(`An item in ${where} has no title.`);
      if (!ITEM_STATUSES.includes(it.status)) out.push(`${name} (${where}) has status "${it.status}"; it is one of ${ITEM_STATUSES.join(', ')}.`);
      if (it.id) {
        if (seen.has(it.id)) out.push(`${it.id} appears twice.`);
        seen.add(it.id);
      }
      if (it.status === 'in_review' && !it.prs?.length) out.push(`${name} is in review with no PR.`);
      if (it.prs && !it.prs.every((n) => Number.isInteger(n) && n > 0)) out.push(`${name} has a PR that is not a number.`);
      if (it.items?.length) walk(it.items, `${where} › ${name}`);
    }
  };
  for (const sec of s.sections ?? []) walk(sec.items, sec.title);
  return out;
}

export function loadStatus(yamlText: string): Status {
  const s = parse(yamlText) as Status;
  const bad = problems(s);
  if (bad.length) throw new Error(`docs/PHASE-32-STATUS.yaml:\n- ${bad.join('\n- ')}`);
  return s;
}

const SUFFIX: Record<ItemStatus, string> = { todo: '', building: ' — building', in_review: ' — in review', done: '' };

function line(it: Item, depth: number): string[] {
  const box = it.status === 'done' ? 'x' : ' ';
  const prs = it.prs?.length ? ` (${it.prs.map((n) => `#${n}`).join(', ')})` : '';
  const text = `${it.followUp ? 'Follow-up: ' : ''}${it.id ? `${it.id} ` : ''}${it.title}${prs}${SUFFIX[it.status]}`;
  return [`${'  '.repeat(depth)}- [${box}] ${text}`, ...(it.items ?? []).flatMap((c) => line(c, depth + 1))];
}

const cell = (s: string) => s.replace(/\|/g, '\\|').replace(/\n+/g, ' ');

/** The LOG's Now and Checklist sections, as Markdown. */
export function renderLog(s: Status): string {
  return [
    START,
    '## Now',
    '',
    '| | |',
    '|---|---|',
    `| **Stage / step** | ${cell(s.now.step)} |`,
    `| **Status** | ${cell(s.now.status)} |`,
    `| **Next action** | ${cell(s.now.next)} |`,
    `| **Blockers** | ${cell(s.now.blockers)} |`,
    `| **Branch** | \`${cell(s.now.branch)}\` |`,
    `| **Last updated** | ${cell(s.now.updated)} |`,
    '',
    '---',
    '',
    '## Checklist',
    '',
    ...s.sections.flatMap((sec) => [`### ${sec.title}`, ...sec.items.flatMap((it) => line(it, 0)), '']),
    END,
  ].join('\n');
}

/** The LOG with its generated block replaced. Throws when the markers are missing. */
export function applyToLog(log: string, s: Status): string {
  const a = log.indexOf(START);
  const b = log.indexOf(END);
  if (a < 0 || b < a) throw new Error('docs/PHASE-32-LOG.md has no status block (its start and end markers)');
  return log.slice(0, a) + renderLog(s) + log.slice(b + END.length);
}

/** Every step with an id, flattened, for anything that wants to ask "what is merged, what is next". */
export function steps(s: Status): Array<Item & { section: string; parent?: string }> {
  const out: Array<Item & { section: string; parent?: string }> = [];
  const walk = (items: Item[], section: string, parent?: string) => {
    for (const it of items) {
      if (it.id) out.push({ ...it, section, parent });
      if (it.items) walk(it.items, section, it.id ?? parent);
    }
  };
  for (const sec of s.sections) walk(sec.items, sec.title);
  return out;
}
