/**
 * Phase 32 status: intent written down, state read from git (the owner's
 * ask, 2026-09-30).
 *
 * The Now block and the checklist were hand-kept Markdown in
 * `docs/PHASE-32-LOG.md`, and they drifted (a Now block still describing the
 * step before). Now `docs/PHASE-32-STATUS.yaml` holds only what git cannot
 * know: the steps, their titles, order and parts, follow-ups, the next action
 * and blockers. Whether a step is building, in review or done, and which PRs
 * carried it, is read from git and GitHub (`git-facts.ts`), because every
 * step has a branch and lands as a squash commit naming its id and PR. A
 * hand-set status is allowed only for what has no branch (`todo` or `done`).
 *
 * `npm run status` writes the LOG's Now and Checklist from both. The block is
 * a snapshot, labelled with the commit it was read at, so a merge elsewhere
 * does not make every open branch fail: the unit test checks that the LOG
 * has the YAML's items in its order, and `npm run status:check` says, where
 * git history is at hand, whether the snapshot is behind.
 */

import { parse } from 'yaml';
import type { Facts } from './git-facts';

export const ITEM_STATUSES = ['todo', 'building', 'in_review', 'done'] as const;
export type ItemStatus = typeof ITEM_STATUSES[number];
/** What a person may write: whether something with no branch is done. The rest is git's. */
export const MANUAL_STATUSES: readonly ItemStatus[] = ['todo', 'done'];

export interface Item {
  /** The step's id when it has one: `B7.4`, `0.4c-1`, `HD1`. Its branch is `feat/phase-32-<id>-…`. */
  id?: string;
  title: string;
  /** Only for what git cannot see (no branch, no PR naming it): todo or done. */
  status?: ItemStatus;
  /** PRs git cannot attribute (their merge commit does not name the id). Git's are added. */
  prs?: number[];
  /** Something found on the way, not a planned step. */
  followUp?: boolean;
  items?: Item[];
}

export interface Section { title: string; items: Item[] }

export interface Now {
  step: string;
  status: string;
  next: string;
  blockers: string;
  updated: string;
}

export interface Status { now: Now; sections: Section[] }

/** An item with its state settled. */
export interface Resolved extends Omit<Item, 'items' | 'status' | 'prs'> {
  status: ItemStatus;
  prs: number[];
  sha?: string;
  branch?: string;
  /** Where the state came from. */
  from: 'git' | 'written' | 'parts' | 'none';
  items: Resolved[];
}

export const START = '<!-- status:start — generated by `npm run status` from docs/PHASE-32-STATUS.yaml and git; edit the YAML, not this block -->';
export const END = '<!-- status:end -->';

/** Why the status cannot be used, one sentence per problem; empty when it can. */
export function problems(s: Status): string[] {
  const out: string[] = [];
  const nowKeys: Array<keyof Now> = ['step', 'status', 'next', 'blockers', 'updated'];
  for (const k of nowKeys) if (typeof s.now?.[k] !== 'string' || !s.now[k].trim()) out.push(`now.${k} is missing.`);
  const seen = new Set<string>();
  const walk = (items: Item[], where: string) => {
    for (const it of items ?? []) {
      const name = it.id ?? it.title?.slice(0, 40);
      if (!it.title?.trim()) out.push(`An item in ${where} has no title.`);
      if (it.status !== undefined && !MANUAL_STATUSES.includes(it.status)) {
        out.push(`${name} (${where}) is written "${it.status}"; only todo or done can be written, the rest is read from git.`);
      }
      if (it.id) {
        if (seen.has(it.id)) out.push(`${it.id} appears twice.`);
        seen.add(it.id);
      }
      if (it.prs && !it.prs.every((n) => Number.isInteger(n) && n > 0)) out.push(`${name} has a PR that is not a number.`);
      if (it.items?.length) walk(it.items, `${where} › ${name}`);
    }
  };
  for (const sec of s.sections ?? []) walk(sec.items, sec.title);
  return out;
}

export function loadStatus(yamlText: string): Status {
  const s = parse(yamlText) as Status;
  const bad = problems(s);
  if (bad.length) throw new Error(`docs/PHASE-32-STATUS.yaml:\n- ${bad.join('\n- ')}`);
  return s;
}

/** Every id in the file, for the git reader. */
export function allIds(s: Status): string[] {
  const out: string[] = [];
  const walk = (items: Item[]) => { for (const it of items) { if (it.id) out.push(it.id); if (it.items) walk(it.items); } };
  for (const sec of s.sections) walk(sec.items);
  return out;
}

/**
 * Settle each item's state. Git's facts win; then what is written; then, for
 * an item with parts, its parts (all done is done, any started is building);
 * otherwise todo.
 */
export function resolve(s: Status, facts: Facts | null): Resolved[][] {
  const one = (it: Item): Resolved => {
    const items = (it.items ?? []).map(one);
    const fact = it.id ? facts?.byId.get(it.id) : undefined;
    const written = it.prs ?? [];
    const base = { ...(it.id ? { id: it.id } : {}), title: it.title, ...(it.followUp ? { followUp: true } : {}), items };
    if (fact) {
      // A PR the title already names (`… (#163) — **M2 done**`) is not said twice.
      const named = new Set([...it.title.matchAll(/#(\d+)/g)].map((m) => Number(m[1])));
      const prs = [...written, ...fact.prs.filter((n) => !written.includes(n) && !named.has(n))];
      return { ...base, status: fact.status, prs, from: 'git', ...(fact.sha ? { sha: fact.sha } : {}), ...(fact.branch ? { branch: fact.branch } : {}) };
    }
    if (it.status) return { ...base, status: it.status, prs: written, from: 'written' };
    if (items.length) {
      const all = items.every((c) => c.status === 'done');
      const any = items.some((c) => c.status !== 'todo');
      return { ...base, status: all ? 'done' : any ? 'building' : 'todo', prs: written, from: 'parts' };
    }
    return { ...base, status: 'todo', prs: written, from: 'none' };
  };
  return s.sections.map((sec) => sec.items.map(one));
}

/** Every resolved item, flattened, with its section. */
export function flatten(s: Status, resolved: Resolved[][]): Array<Resolved & { section: string }> {
  const out: Array<Resolved & { section: string }> = [];
  const walk = (items: Resolved[], section: string) => { for (const it of items) { out.push({ ...it, section }); walk(it.items, section); } };
  s.sections.forEach((sec, i) => walk(resolved[i], sec.title));
  return out;
}

const SUFFIX: Record<ItemStatus, string> = { todo: '', building: ' — building', in_review: ' — in review', done: '' };

/** One checklist line (and its parts). */
function line(it: Resolved, depth: number): string[] {
  const box = it.status === 'done' ? 'x' : ' ';
  const prs = it.prs.length ? ` (${it.prs.map((n) => `#${n}`).join(', ')})` : '';
  const text = `${it.followUp ? 'Follow-up: ' : ''}${it.id ? `${it.id} ` : ''}${it.title}${prs}${SUFFIX[it.status]}`;
  return [`${'  '.repeat(depth)}- [${box}] ${text}`, ...it.items.flatMap((c) => line(c, depth + 1))];
}

const cell = (s: string) => s.replace(/\|/g, '\\|').replace(/\n+/g, ' ');

/** The LOG's Now and Checklist sections, as Markdown. */
export function renderLog(s: Status, facts: Facts | null): string {
  const resolved = resolve(s, facts);
  const flat = flatten(s, resolved).filter((x) => x.id);
  const inFlight = flat.filter((x) => x.from === 'git' && (x.status === 'in_review' || x.status === 'building'))
    .map((x) => `${x.id} ${x.status === 'in_review' ? `in review (${x.prs.map((n) => `#${n}`).join(', ')})` : 'building'} on \`${x.branch}\``)
    .concat((facts?.otherOpen ?? []).map((p) => `#${p.number} in review on \`${p.branch}\``));
  const merged = facts
    ? flat.filter((x) => x.from === 'git' && x.status === 'done' && x.sha).sort((a, b) => Math.max(...b.prs) - Math.max(...a.prs))[0]
    : undefined;
  const readAt = facts
    ? `Read from git at \`${facts.base}\` \`${facts.baseSha}\`${facts.source === 'github' ? ', with open PRs from GitHub' : ' (offline: only the branch checked out counts as building)'}.`
    : 'Not read from git: statuses are only what the YAML writes.';
  return [
    START,
    '## Now',
    '',
    '| | |',
    '|---|---|',
    `| **Stage / step** | ${cell(s.now.step)} |`,
    `| **Status** | ${cell(s.now.status)} |`,
    `| **In flight** | ${cell(inFlight.length ? inFlight.join('; ') : 'nothing open')} |`,
    `| **Last merged** | ${cell(merged ? `${merged.id} (${merged.prs.map((n) => `#${n}`).join(', ')}, \`${merged.sha}\`)` : '—')} |`,
    `| **Next action** | ${cell(s.now.next)} |`,
    `| **Blockers** | ${cell(s.now.blockers)} |`,
    `| **Last updated** | ${cell(s.now.updated)} |`,
    '',
    `> ${readAt}`,
    '',
    '---',
    '',
    '## Checklist',
    '',
    ...s.sections.flatMap((sec, i) => [`### ${sec.title}`, ...resolved[i].flatMap((it) => line(it, 0)), '']),
    END,
  ].join('\n');
}

/** The LOG with its generated block replaced. Throws when the markers are missing. */
export function applyToLog(log: string, s: Status, facts: Facts | null): string {
  const a = log.indexOf(START);
  const b = log.indexOf(END);
  if (a < 0 || b < a) throw new Error('docs/PHASE-32-LOG.md has no status block (its start and end markers)');
  return log.slice(0, a) + renderLog(s, facts) + log.slice(b + END.length);
}

/**
 * The item lines of a rendered checklist with the state taken out (box, PRs,
 * "— in review"), so two renderings can be compared for the items alone.
 */
export function intentLines(block: string): string[] {
  const from = block.indexOf('## Checklist');
  return block.slice(from).split('\n')
    .filter((l) => /^\s*- \[[ x]\] /.test(l) || l.startsWith('### '))
    .map((l) => l.replace(/^(\s*)- \[[ x]\] /, '$1- ').replace(/ — (building|in review)$/, '').replace(/ \((#\d+(, #\d+)*)\)$/, ''));
}

/** The generated block of a LOG, or null. */
export function blockOf(log: string): string | null {
  const a = log.indexOf(START);
  const b = log.indexOf(END);
  return a >= 0 && b > a ? log.slice(a, b + END.length) : null;
}
