/**
 * Auto-generated by scripts/generate-build-info.js — DO NOT EDIT BY HAND.
 *
 * The file IS committed (rather than gitignored) so:
 *   - typecheck doesn't fail on a fresh clone before the prebuild
 *     hook has run
 *   - the dev backend (run via tsx) can import it without an extra
 *     build step
 *
 * The `prepackage` npm script re-runs this at packaging time so
 * the DMG / EXE always carries fresh metadata.
 */
export interface BuildInfo {
  version: string;
  buildTime: string;       // ISO 8601
  buildNumber: number;     // commit count from HEAD; monotonic
  commit: string;          // full SHA
  commitShort: string;     // 7-char SHA
  branch: string;
  dirty: boolean;          // working tree had uncommitted changes at build
}

export const BUILD_INFO: BuildInfo = {
  "version": "0.1.9",
  "buildTime": "2026-05-26T14:16:12.964Z",
  "buildNumber": 228,
  "commit": "56cd7f1b7dd50c38654f97644edc4de60d35a770",
  "commitShort": "56cd7f1",
  "branch": "main",
  "dirty": false
};
