/**
 * Public half of the release-manifest signing key.
 *
 * COMMITTED ON PURPOSE. A running copy of CodeTrellis has to be able to check
 * that a downloaded installer is one we published, without asking a server
 * whose answer it would then have to trust.
 *
 * The private half lives on the release machine only (gitignored), and is
 * never in CI. Generated by `scripts/generate-signing-key.js` — do not edit
 * this file by hand.
 *
 * Replacing this key is a breaking change for anyone running an older build:
 * they carry the old public key and will not be able to verify releases signed
 * with the new one.
 */
export const RELEASE_PUBLIC_KEY_PEM = `-----BEGIN PUBLIC KEY-----
MCowBQYDK2VwAyEAUtfyemenyMhyJbIIuJDrc3NX8Ck8YtYKkn31XTzhZSY=
-----END PUBLIC KEY-----
`;
