/**
 * Terminal history — Session-persistence plan §7.5.
 *
 * Per-terminal append-only on-disk log that captures the raw PTY
 * output stream (ANSI intact) so users can scroll back through far
 * more than the 256KB in-memory ring buffer holds. The disk log
 * survives terminal-detail un-mount and CodeTrellis restarts; it is
 * the durable counterpart to the in-memory ring in `terminal-service.ts`.
 *
 * Design (hybrid, per plan body recommendation):
 *   - In-memory ring stays the hot path for live reads (zero added
 *     latency for `terminal.stream` poll).
 *   - Writes also flow here, buffered and batched to disk (avoid
 *     blocking the PTY data callback at the request frequency).
 *   - Reads via `getHistoryChunk(id, before?, limit)` walk backwards
 *     through the file by absolute byte offset.
 *
 * Cap: per-terminal hard limit. Once hit, further appends are dropped
 * (the in-memory ring still cycles, so live reads still work — only
 * older history beyond the cap is unavailable). v1 doesn't rotate;
 * rotation can land in a follow-up if real sessions hit the cap.
 *
 * Storage location: `<dataDir>/terminals/<id>.log`. Never synced via
 * the personal-sync path (the persistence service handles dir scoping
 * separately) — terminal output can contain secrets.
 */

import fs from 'node:fs';
import path from 'node:path';
import { getDataDir } from './persistence';

/** Per-terminal hard cap. Many hours of an interactive session. */
const PER_TERMINAL_CAP_BYTES = 200 * 1024 * 1024; // 200 MB
/**
 * Global cap across all terminal history files on disk. When exceeded,
 * the oldest files (by mtime) are deleted until the total is back
 * under cap. Live sessions are *never* deleted regardless of mtime.
 *
 * 5 GB is generous — typical interactive output compresses well and
 * 5 GB of raw ANSI is roughly months of busy sessions.
 */
const GLOBAL_HISTORY_CAP_BYTES = 5 * 1024 * 1024 * 1024; // 5 GB
/** Pending writes are batched + flushed at the first of:
 *  - WRITE_FLUSH_INTERVAL_MS since the previous flush
 *  - WRITE_FLUSH_BYTES of pending data
 *  - explicit flush() (e.g., before a read) */
const WRITE_FLUSH_INTERVAL_MS = 1_000;
const WRITE_FLUSH_BYTES = 16 * 1024;
/** Default read chunk if the caller doesn't specify. ~5-10 screens
 *  of typical output. */
const DEFAULT_READ_CHUNK_BYTES = 64 * 1024;

interface TerminalLog {
  fd: number;
  pendingWrites: string[];
  pendingBytes: number;
  flushTimer: ReturnType<typeof setTimeout> | null;
  /** Total bytes written to disk so far (== file size). */
  bytesWritten: number;
  /** True once bytesWritten + pendingBytes ≥ cap — further appends drop. */
  capped: boolean;
}

const logs = new Map<string, TerminalLog>();

function getTerminalsDir(): string {
  return path.join(getDataDir(), 'terminals');
}

/**
 * Terminal ids we will turn into a filename.
 *
 * Phase 19, finding 7. The id arrives from a request and was interpolated
 * straight into a path, so `../../../etc/passwd` escaped the terminals
 * directory. Terminal ids are generated by this app and look like
 * `term-1-mu4p78x9`, so a strict allowlist costs nothing.
 */
const SAFE_TERMINAL_ID = /^[A-Za-z0-9_-]{1,128}$/;

function assertSafeTerminalId(terminalId: string): string {
  if (!SAFE_TERMINAL_ID.test(terminalId)) {
    throw new Error(
      `Invalid terminal id "${String(terminalId).slice(0, 64)}" — ` +
        'ids may contain only letters, digits, underscore and hyphen.',
    );
  }
  return terminalId;
}

function getLogPath(terminalId: string): string {
  return path.join(getTerminalsDir(), `${assertSafeTerminalId(terminalId)}.log`);
}

/**
 * Open (creating if needed) the append handle for a terminal.
 *
 * WRITE PATH ONLY. Reads must not come through here — see `openLogForRead`.
 */
function ensureLog(terminalId: string): TerminalLog {
  assertSafeTerminalId(terminalId);
  let log = logs.get(terminalId);
  if (log) return log;

  const dir = getTerminalsDir();
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  const filePath = getLogPath(terminalId);
  // 'a+' = read + append. Writes always go to EOF; reads accept an
  // explicit position arg so we can walk backwards.
  const fd = fs.openSync(filePath, 'a+');
  const stat = fs.fstatSync(fd);
  log = {
    fd,
    pendingWrites: [],
    pendingBytes: 0,
    flushTimer: null,
    bytesWritten: stat.size,
    capped: stat.size >= PER_TERMINAL_CAP_BYTES,
  };
  logs.set(terminalId, log);
  return log;
}

function flushLog(log: TerminalLog): void {
  if (log.pendingWrites.length === 0) {
    if (log.flushTimer) { clearTimeout(log.flushTimer); log.flushTimer = null; }
    return;
  }
  const buf = Buffer.from(log.pendingWrites.join(''), 'utf-8');
  log.pendingWrites = [];
  log.pendingBytes = 0;
  if (log.flushTimer) { clearTimeout(log.flushTimer); log.flushTimer = null; }
  try {
    fs.writeSync(log.fd, buf);
    log.bytesWritten += buf.length;
    if (log.bytesWritten >= PER_TERMINAL_CAP_BYTES) log.capped = true;
  } catch (err) {
    console.warn('[TerminalHistory] flush failed:', err);
  }
}

/**
 * Append a chunk of PTY output to the on-disk log. Buffered + flushed
 * asynchronously so the caller (PTY data callback) is never blocked.
 * Silently drops once the per-terminal cap is hit.
 */
export function appendHistory(terminalId: string, data: string): void {
  if (data.length === 0) return;
  const log = ensureLog(terminalId);
  if (log.capped) return;
  log.pendingWrites.push(data);
  log.pendingBytes += Buffer.byteLength(data, 'utf-8');
  if (log.pendingBytes >= WRITE_FLUSH_BYTES) {
    flushLog(log);
    return;
  }
  if (!log.flushTimer) {
    log.flushTimer = setTimeout(() => {
      const current = logs.get(terminalId);
      if (current) flushLog(current);
    }, WRITE_FLUSH_INTERVAL_MS);
  }
}

/**
 * Read a chunk of history ending at `before` (absolute byte offset
 * into the file). Omit `before` to start at the tail (file size).
 * Returns the data + the offset to pass on the next call to walk
 * further back + `hasMore` if there's still earlier content + the
 * current `fileSize` so the caller knows the total range.
 */
/**
 * Read scrollback for a terminal with no open handle.
 *
 * Opens 'r' — read-only, never creates. A terminal that was never opened,
 * or whose log has been cleaned up, reads as empty rather than springing
 * into existence.
 */
function readClosedLog(
  terminalId: string,
  before: number | undefined,
  limit: number,
): { data: string; prevOffset: number; hasMore: boolean; fileSize: number; capped: boolean } {
  const empty = { data: '', prevOffset: 0, hasMore: false, fileSize: 0, capped: false };
  let fd: number | null = null;
  try {
    fd = fs.openSync(getLogPath(terminalId), 'r');
    const fileSize = fs.fstatSync(fd).size;
    let endOffset = before ?? fileSize;
    if (endOffset > fileSize) endOffset = fileSize;
    const startOffset = Math.max(0, endOffset - limit);
    const readLen = endOffset - startOffset;
    if (readLen <= 0) return { ...empty, fileSize };
    const buf = Buffer.alloc(readLen);
    fs.readSync(fd, buf, 0, readLen, startOffset);
    return {
      data: buf.toString('utf-8'),
      prevOffset: startOffset,
      hasMore: startOffset > 0,
      fileSize,
      capped: fileSize >= PER_TERMINAL_CAP_BYTES,
    };
  } catch {
    // ENOENT is the normal case for a terminal that never wrote anything.
    return empty;
  } finally {
    if (fd !== null) {
      try { fs.closeSync(fd); } catch { /* */ }
    }
  }
}

export function getHistoryChunk(
  terminalId: string,
  before: number | undefined,
  limit: number = DEFAULT_READ_CHUNK_BYTES,
): { data: string; prevOffset: number; hasMore: boolean; fileSize: number; capped: boolean } {
  assertSafeTerminalId(terminalId);

  // A READ MUST NOT CREATE A FILE (Phase 19, finding 7).
  //
  // This used to call `ensureLog`, which opens with 'a+' — append-or-create.
  // So asking to read the scrollback of a terminal that does not exist
  // CREATED it, and with a traversable id that was arbitrary file creation
  // anywhere the process could write.
  //
  // An already-open handle is reused (the live terminal case, where the
  // buffered writes need flushing first). Otherwise the file is opened
  // read-only, and a missing file is simply empty history.
  const existing = logs.get(terminalId);
  if (!existing) {
    return readClosedLog(terminalId, before, limit);
  }
  const log = existing;
  // Flush so reads see the latest buffered writes.
  flushLog(log);

  const fileSize = log.bytesWritten;
  let endOffset = before ?? fileSize;
  if (endOffset > fileSize) endOffset = fileSize;
  const startOffset = Math.max(0, endOffset - limit);
  const readLen = endOffset - startOffset;
  if (readLen <= 0) {
    return { data: '', prevOffset: 0, hasMore: false, fileSize, capped: log.capped };
  }
  const buf = Buffer.alloc(readLen);
  try {
    fs.readSync(log.fd, buf, 0, readLen, startOffset);
  } catch (err) {
    console.warn('[TerminalHistory] read failed:', err);
    return { data: '', prevOffset: 0, hasMore: false, fileSize, capped: log.capped };
  }
  return {
    data: buf.toString('utf-8'),
    prevOffset: startOffset,
    hasMore: startOffset > 0,
    fileSize,
    capped: log.capped,
  };
}

/** Total bytes recorded for this terminal. */
export function getHistorySize(terminalId: string): number {
  assertSafeTerminalId(terminalId);
  const log = logs.get(terminalId);
  if (log) return log.bytesWritten;
  // Hasn't been opened this session — peek at the file on disk.
  try {
    return fs.statSync(getLogPath(terminalId)).size;
  } catch {
    return 0;
  }
}

/**
 * Close the disk handle for a terminal (e.g., when it's killed).
 * The log file is left on disk so a subsequent open can still scroll
 * through it. GC of dead-terminal logs is a follow-up item.
 */
export function closeTerminalHistory(terminalId: string): void {
  const log = logs.get(terminalId);
  if (!log) return;
  flushLog(log);
  try { fs.closeSync(log.fd); } catch { /* */ }
  logs.delete(terminalId);
}

/** Flush + close every open log. Call on server shutdown. */
export function closeAllTerminalHistory(): void {
  for (const id of Array.from(logs.keys())) {
    closeTerminalHistory(id);
  }
}

/**
 * Plan 11.3 — startup sweep. Called from initializeBackend().
 *
 * Walks the on-disk terminals directory once at boot:
 *   1. Logs how many .log files exist + their total size (so the
 *      desktop log shows where the disk is going).
 *   2. Enforces the global cap (`GLOBAL_HISTORY_CAP_BYTES`) by
 *      deleting the oldest-by-mtime files until total ≤ cap. Live
 *      sessions are never deleted (we just opened, so `logs` is
 *      empty at this point — but we check anyway for re-entry
 *      safety).
 *
 * Does NOT close orphan fds from a previous process — those went
 * with the process death. Open fds for active sessions only happen
 * after the first append, so this sweep is safe to run before any
 * terminal is created.
 *
 * Idempotent + best-effort: errors are logged but do not throw,
 * because terminal history is a soft-fail subsystem (live reads
 * still work via the in-memory ring even if disk is unavailable).
 */
export function initTerminalHistory(): void {
  const dir = getTerminalsDir();
  if (!fs.existsSync(dir)) {
    // No prior history yet — nothing to sweep. The dir is created
    // lazily by `ensureLog`.
    return;
  }
  let files: fs.Dirent[];
  try {
    files = fs.readdirSync(dir, { withFileTypes: true });
  } catch (err) {
    console.warn('[TerminalHistory] init: readdir failed:', err);
    return;
  }
  const logFiles: Array<{ path: string; size: number; mtimeMs: number; id: string }> = [];
  let totalBytes = 0;
  for (const f of files) {
    if (!f.isFile() || !f.name.endsWith('.log')) continue;
    const full = path.join(dir, f.name);
    try {
      const stat = fs.statSync(full);
      const id = f.name.slice(0, -'.log'.length);
      logFiles.push({ path: full, size: stat.size, mtimeMs: stat.mtimeMs, id });
      totalBytes += stat.size;
    } catch { /* file vanished between readdir + stat — skip */ }
  }
  console.log(
    `[TerminalHistory] init — ${logFiles.length} log file(s), ` +
    `total ${Math.round(totalBytes / 1024 / 1024)} MB ` +
    `(cap ${Math.round(GLOBAL_HISTORY_CAP_BYTES / 1024 / 1024)} MB)`,
  );
  if (totalBytes <= GLOBAL_HISTORY_CAP_BYTES) return;

  // Over cap — delete oldest first. Skip any file whose id is in the
  // live `logs` map (we just opened it; shouldn't happen at boot but
  // safe for re-entry).
  const candidates = logFiles
    .filter((f) => !logs.has(f.id))
    .sort((a, b) => a.mtimeMs - b.mtimeMs);
  let deleted = 0;
  let bytesFreed = 0;
  for (const f of candidates) {
    if (totalBytes <= GLOBAL_HISTORY_CAP_BYTES) break;
    try {
      fs.unlinkSync(f.path);
      totalBytes -= f.size;
      bytesFreed += f.size;
      deleted++;
    } catch (err) {
      console.warn(`[TerminalHistory] init: failed to delete ${f.path}:`, err);
    }
  }
  if (deleted > 0) {
    console.log(
      `[TerminalHistory] init — pruned ${deleted} file(s), ` +
      `freed ${Math.round(bytesFreed / 1024 / 1024)} MB`,
    );
  }
}
